ToDoList/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoList.Models;
using ToDoList.Services;
using ToDoList.ViewModel;

namespace ToDoList.Controllers
{
    public class TaskController : Controller
    {
        private TaskService _service;
        public TaskController()
        {
            _service = new TaskService();
        }

        private void createViewBagForView()
        {
            List<TaskStatu> taskStatus = _service.GetAllTaskStatus();
            List<Employee> employee = _service.GetAllEmployee();

            SelectList listEmployee = new SelectList(employee, "Id", "Name", 0);
            SelectList listStatus = new SelectList(taskStatus, "Id", "StatusName", 1);
            ViewBag.listEmployee = listEmployee;
            ViewBag.listStatus = listStatus;
            
        }

        // GET: Task
        public ActionResult Index(string searchString, string currentFilter,string filterByTaskStatus, int pageIndex = 1)
        {

            if (Session["userId"] != null)
            {
                if (Session["role"].Equals("2"))
                {
                    int userId = Convert.ToInt32(Session["userId"]);
                    if (searchString != null)
                    {
                        pageIndex = 1;
                    }
                    else
                    {
                        searchString = currentFilter;
                    }
                    List<TaskStatu> listTaskStatus = _service.GetAllTaskStatus();
                    //ViewBag.listTaskStatus = 
                    if(String.IsNullOrEmpty(filterByTaskStatus))
                    {

                    }

                    ViewBag.currentFilter = searchString;
                    TaskIndexVM vm = _service.getAllTaskOfUser(searchString, pageIndex, userId);
                    return View(vm);
                }
                else
                {
                    if (searchString != null)
                    {
                        pageIndex = 1;
                    }
                    else
                    {
                        searchString = currentFilter;
                    }
                    ViewBag.currentFilter = searchString;
                    TaskIndexVM vm = _service.getAllTask(searchString, pageIndex);
                    return View(vm);
                }

            }
            return RedirectToAction("Index", "Account");
        }


        public ActionResult PublicTask(string searchString, string currentFilter, string filterByTaskStatus, int pageIndex = 1)
        {
            if(Session["userId"] == null || Session["role"].ToString().Equals("1") || Session["role"].ToString().Equals("3"))
            {
                return RedirectToAction("Index", "Account");
            }

            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.currentFilter = searchString;
            TaskIndexVM vm = _service.getAllPublicTask(searchString, pageIndex);
            return View(vm);
        }

        [HttpPost]
        public void autoUpdateTask()
        {
            _service.autoUpdateTask();
        }

        public ActionResult Create()
        {
            if (Session["userId"] != null)
            {
                createViewBagForView();

                return View(new TaskCreateVM());

            }
            return RedirectToAction("Index", "Account");
        }

        private bool dateValid(DateTime start,DateTime end)
        {
            if (DateTime.Compare(start, end) < 0)
                return true;
            return false;
        }

        [HttpPost]
        public ActionResult Create(TaskCreateVM TaskCreateVM)
        {
            if (Session["userId"] != null)
            {
                //Valid input
                bool flag = true;
                DateTime defaultDate = new DateTime(1,1,1);
                DateTime now = DateTime.Now;

                if(string.IsNullOrEmpty(TaskCreateVM.Title))
                {
                    ViewBag.errorTitle = "Vui lòng nhập tiêu đề";
                    flag = false;
                }
                if(DateTime.Compare(TaskCreateVM.StartDate,defaultDate) == 0)
                {
                    ViewBag.errorStartDate = "Vui lòng chọn thời điểm bắt đầu";
                    flag = false;
                }
                if (DateTime.Compare(TaskCreateVM.EndDate, defaultDate) == 0)
                {
                    ViewBag.errorEndDate = "Vui lòng chọn thời điểm kết thúc";
                    flag = false;
                }
                if(TaskCreateVM.StartDate != null && TaskCreateVM.EndDate != null && ViewBag.errorEndDate == null )
                {
                    if (!dateValid(TaskCreateVM.StartDate, TaskCreateVM.EndDate))
                    {
                        ViewBag.ErrorEndDate = "Thời điểm bắt đầu phải lớn hơn thời điểm kết thúc";
                        flag = false;
                    }
                }
                if( DateTime.Compare(now,TaskCreateVM.EndDate)  > 0 && ViewBag.errorEndDate == null)
                {
                    ViewBag.errorEndDate = "Thời điểm kết thúc phải lớn hơn hiện tại";
                    flag = false;
                }
                if (TaskCreateVM.EmployeeIsAssigned == null && Session["role"].ToString().Equals("1"))
                {
                    ViewBag.ErrorEmployeeIsAssigned = "Vui lòng phân công";
                    flag = false;
                }
                if (TaskCreateVM.File != null && TaskCreateVM.File.Count(file => file != null) != 0)
                {
                    foreach (HttpPostedFileBase item in TaskCreateVM.File)
                    {
                        if (item.ContentLength >= 4 * 1024 * 1024)
                        {
                            ViewBag.fileError = "Dung lượng tệp đính kèm không được lớn hơn 4mb";
                            flag = false;
                            break;
                        }
                    }
                }

                if (flag == false)
                {
                    createViewBagForView();
                    return View(TaskCreateVM);
                }


                else if(ModelState.IsValid )
                {
                    //Add Task
                    Task task = new Task();
                    task.EndDate = TaskCreateVM.EndDate;
                    task.StartDate = TaskCreateVM.StartDate;
                    task.Scope = TaskCreateVM.Scope;
                    task.Title = TaskCreateVM.Title;
                    task.StatusId = TaskCreateVM.StatusId;

                    _service.Add(task);

                    if(Session["role"].ToString().Equals("1"))
                    {
                        //assign admin first to db
                        Assignment admin = new Assignment();
                        admin.EmployeeId = ParseSessionUserIdToInt();
                        admin.TaskId = task.Id;
                        _service.AddAssignment(admin);

                        foreach (int employeeId in TaskCreateVM.EmployeeIsAssigned)
                        {
                            Assignment a = new Assignment();
                            a.EmployeeId = employeeId;
                            a.TaskId = task.Id;
                            _service.AddAssignment(a);
                        }

                    }
                    else
                    {
                        Assignment a = new Assignment();
                        a.EmployeeId = ParseSessionUserIdToInt();
                        a.TaskId = task.Id;

                        _service.AddAssignment(a);
                    }

                    //upload file
                    if (TaskCreateVM.File != null && TaskCreateVM.File.Count(file => file != null) != 0)
                    {
                        foreach(HttpPostedFileBase file in TaskCreateVM.File)
                        {
                            //Use Namespace called :  System.IO  
                            string FileName = Path.GetFileNameWithoutExtension(file.FileName).Trim();

                            //To Get File Extension  
                            string FileExtension = Path.GetExtension(file.FileName);

                            //Add Current Date To Attached File Name  

                            //Get Upload path from Web.Config file AppSettings.  
                            string UploadPath = Server.MapPath(@"\File\");

                            //string path = UploadPath + FileName + FileExtension;
                            //Its Create complete path to store in server.  
                            //FileName += FileExtension;
                            String fullName = FileName + FileExtension;
                            if (_service.isFileNameDuplicate(fullName))
                            {
                                fullName = _service.createFileName(1, _service.GetAllFileManager(), FileName, FileExtension, fullName);
                            }

                            //Add to file manager
                            FileManager fileManager = new FileManager();
                            fileManager.C_Path = fullName;
                            fileManager.TaskId = task.Id;

                            _service.AddFileManager(fileManager);

                            //To copy and save file into server.  
                            file.SaveAs(UploadPath + fullName);

                        }

                    }

                    //Write Log
                    TaskLog tl = new TaskLog();
                    tl.TaskId = task.Id;
                    tl.Content = "Đã khởi tạo công việc";

ToDoList/Views/Shared/StatiscalExpiredTask.cshtml
@model ToDoList.ViewModel.StatisticalIndexVM
<div class="table-responsive table-striped">
    <!-- PROJECT TABLE -->
    <table class="table colored-header datatable project-list table-striped" id="dataTableSt">
        <thead class="thead-dark">
            <tr>
                <th>Stt</th>
                <th>Họ tên nhân viên</th>
                <th>Số lượng công việc trễ hạn</th>
                <th>Hành động</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.statisticalExpiredTasks.Count <= 0)
            {
                <tr>
                    <td colspan="7" style="text-align:center"><i>Không có dữ liệu phù hợp với tiêu chí thống kê</i></td>
                </tr>
            }
            @{
                int stt = 0;
            }
            @foreach (var item in Model.statisticalExpiredTasks)
            {
                ++stt;
                <tr>
                    <td><a href="#">@stt</a></td>
                  
                    <td>@item.Name</td>
                    <td>@item.NumberOfTaskExpired</td>
                    <td><button type="button" class="btn btn-outline-secondary expiredTask" data-employeeId="@item.EmployeeId" data-toggle="modal" data-target="#expiredTaskDetail">Chi tiết</button></td>
                </tr>
             }
        </tbody>
    </table>
    @{
        var disNext = !Model.statisticalExpiredTasks.HasNext ? " visibility: hidden" : "";
        var disPre = !Model.statisticalExpiredTasks.HasPrevious ? " visibility: hidden" : "";
    }
    <ul id="paginationExpiredTask" class="pagination justify-content-end" style="margin:20px 0">
        <li class="page-item">
            <a class="page-link" style="@disPre"
               href="" data-pageIndex="1"><<</a>
        </li>
        <li class="page-item">
            <a class="page-link" style="@disPre"
               href="" data-pageIndex="@Model.statisticalExpiredTasks.PageIndex - 1"><</a>
        </li>
        @{
            for (int i = 1; i <= Model.statisticalExpiredTasks.TotalPages; i++)
            {
                //Nếu số tổng số trang >=8 thì sẽ hiện ... và sẽ hiện trang : i-2 , i-1 , i , i+1 ,i+2
                if (Model.statisticalExpiredTasks.TotalPages >= 8 && @i >= Model.statisticalExpiredTasks.PageIndex - 2 && @i <= Model.statisticalExpiredTasks.PageIndex + 2)
                {
                    if (@i == Model.statisticalExpiredTasks.PageIndex - 2 && @i > 1)
                    {
                        <li class="page-item"><a class="page-link" data-pageIndex="">...</a></li>
                    }
                    if (@i == Model.statisticalExpiredTasks.PageIndex)
                    {
                        <li class="page-item active">
                            <a class="page-link " data-pageIndex="@i"> @i </a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item ">
                            <a class="page-link"
                               href="" data-pageIndex="@i">@i</a>
                        </li>
                    }
                    if (@i == Model.statisticalExpiredTasks.PageIndex + 2 && @i < Model.statisticalExpiredTasks.TotalPages)
                    {
                        <li class="page-item"><a class="page-link" data-pageIndex="">...</a></li>
                    }
                }
                else if (Model.statisticalExpiredTasks.TotalPages < 8) //Nếu số tổng số trang <8 thì sẽ hiện hết các trang
                {
                    if (@i == Model.statisticalExpiredTasks.PageIndex)
                    {
                        <li class="page-item active">
                            <a class="page-link " data-pageIndex="@i"> @i </a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link"
                               href="" data-pageIndex="@i">@i</a>
                        </li>
                    }
                }
            }
        }
        <li class="page-item">
            @{
                var nextPage = Model.statisticalExpiredTasks.PageIndex + 1;
            }
            <a class="page-link" style="@disNext" data-pageIndex="@nextPage"
               href="">></a>
        </li>
        <li class="page-item">
            @{
                var totalPage = Model.statisticalExpiredTasks.TotalPages;
            }
            <a class="page-link" style="@disNext" data-pageIndex="@totalPage"
               href="">>></a>
        </li>
    </ul>
    <!-- END PROJECT TABLE -->
</div>
<script>
    $(document).ready(function () {

        var loadStatiscalExpiredTaskDetail = function (startDate, endDate, userId, pageIndex) {
            $.ajax({
                type: "Get",
                url: "/Statistical/loadStatiscalExpiredTaskDetail",
                data: {startDate: startDate, endDate:endDate,  userId: userId, pageIndex: pageIndex },
                success: function (response) {
                    $("#modalEmployeeId").val(userId);
                    $("#displayModalData").html(response);
                }
            })
        }

        //click event load expired task of specific employee
        $(".expiredTask").click(function () {
            var employeeId = $(this).attr('data-employeeId');
            var startDate = $("#startDate").val();
            var endDate = $("#endDate").val();
            loadStatiscalExpiredTaskDetail(startDate, endDate, employeeId, 1)
        })

        //click event pagination for statistical expired task detail
        $("body").on("click", "#detailExpiredTask li a", function (event) {
            event.preventDefault();
            var pageIndex = $(this).attr('data-pageIndex');
            var userId = $("#modalEmployeeId").val();
            var startDate = $("#startDate").val();
            var endDate = $("#endDate").val();
            loadStatiscalExpiredTaskDetail(startDate, endDate, userId, pageIndex)
        });

    })
</script>

ToDoList/Views/Shared/StatisticalTaskByStatus.cshtml
@model ToDoList.ViewModel.StatisticalIndexVM
<div class="table-responsive table-striped">
    <!-- PROJECT TABLE -->
    <table class="table colored-header datatable project-list" id="dataTableSt">
        <thead class="thead-dark">
            <tr>
                <th>Tiêu đề</th>
                <th>Ngày bắt đầu</th>
                <th>Ngày kết thúc</th>
                <th>Phạm vi</th>
                <th>Người tạo</th>
                <th>Trạng thái</th>
                <th>Hành động</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.statisticalTasks.Count <= 0)
            {
                <tr>
                    <td colspan="7" style="text-align:center"><i>Không có dữ liệu phù hợp với tiêu chí thống kê</i></td>
                </tr>
            }
            @foreach (var item in Model.statisticalTasks)
            {
                <tr>
                    <td><a href="#">@item.Title</a></td>
                    @{
                        var startDate = item.StartDate.ToString("dd/MM/yyyy HH:MM tt");
                        var endDate = item.EndDate.ToString("dd/MM/yyyy HH:MM tt");
                        var statusId = item.statusId;
                        var statusText = ""; // 1. Đang làm 2. Đã xong 3. Trễ hạn
                        var statusColor = "";
                        if (statusId == 1)
                        {
                            statusText = "Đang làm";
                            statusColor = "label-info";
                        }
                        else if (statusId == 2)
                        {
                            statusText = "Đã xong";
                            statusColor = "label-success";
                        }
                        else
                        {
                            statusText = "Trễ hạn";
                            statusColor = "label-danger";
                        }
                        var labelScopeColor = item.Scope ? "label-primary" : "label-warning";
                        var labelScopeText = item.Scope ? "public" : "private";
                    }
                    <td>@startDate</td>
                    <td>@endDate</td>
                    <td>
                        <span class="label @labelScopeColor">@labelScopeText</span>
                    </td>
                    <td><img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="Avatar" class="avatar img-circle"> <a href="#">@item.Creator</a></td>
                    <td><span class="label @statusColor">@statusText</span></td>
                    <td><button type="button" class="btn btn-outline-secondary"><a href="@Url.Action("Detail", "Task", new { id=item.Id })" style="text-decoration:none; color: black;">Chi tiết</a></button></td>
                </tr>
                        }
        </tbody>
    </table>
    @{
        var disNext = !Model.statisticalTasks.HasNext ? " visibility: hidden" : "";
        var disPre = !Model.statisticalTasks.HasPrevious ? " visibility: hidden" : "";
    }
    <ul id="paginationStatusOfTask" class="pagination justify-content-end" style="margin:20px 0">
        <li class="page-item">
            <a class="page-link" style="@disPre"
               href="" data-pageIndex="1"><<</a>
        </li>
        <li class="page-item">
            <a class="page-link" style="@disPre"
               href="" data-pageIndex="@Model.statisticalTasks.PageIndex - 1"><</a>
        </li>
        @{
            for (int i = 1; i <= Model.statisticalTasks.TotalPages; i++)
            {
                //Nếu số tổng số trang >=8 thì sẽ hiện ... và sẽ hiện trang : i-2 , i-1 , i , i+1 ,i+2
                if (Model.statisticalTasks.TotalPages >= 8 && @i >= Model.statisticalTasks.PageIndex - 2 && @i <= Model.statisticalTasks.PageIndex + 2)
                {
                    if (@i == Model.statisticalTasks.PageIndex - 2 && @i > 1)
                    {
                        <li class="page-item"><a class="page-link" data-pageIndex="">...</a></li>
                    }
                    if (@i == Model.statisticalTasks.PageIndex)
                    {
                        <li class="page-item active">
                            <a class="page-link " data-pageIndex="@i"> @i </a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item ">
                            <a class="page-link"
                               href="" data-pageIndex="@i">@i</a>
                        </li>
                    }
                    if (@i == Model.statisticalTasks.PageIndex + 2 && @i < Model.statisticalTasks.TotalPages)
                    {
                        <li class="page-item"><a class="page-link" data-pageIndex="">...</a></li>
                    }
                }
                else if (Model.statisticalTasks.TotalPages < 8) //Nếu số tổng số trang <8 thì sẽ hiện hết các trang
                {
                    if (@i == Model.statisticalTasks.PageIndex)
                    {
                        <li class="page-item active">
                            <a class="page-link " data-pageIndex="@i"> @i </a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link"
                               href="" data-pageIndex="@i">@i</a>
                        </li>
                    }
                }
            }
        }
        <li class="page-item">
            @{
                var nextPage = Model.statisticalTasks.PageIndex + 1;
            }
            <a class="page-link" style="@disNext" data-pageIndex="@nextPage"
               href="">></a>
        </li>
        <li class="page-item">
            @{
                var totalPage = Model.statisticalTasks.TotalPages;
            }
            <a class="page-link" style="@disNext" data-pageIndex="@totalPage"
               href="">>></a>
        </li>
    </ul>
    <!-- END PROJECT TABLE -->
</div>

ToDoList/Views/Shared/_CommentPartial.cshtml
@model ToDoList.ViewModel.DetailTaskVM

@foreach (var item in Model.Comments)
{
    var srcImage = "";
    var badgeColor = "";
    var text = "";
    if (item.Role.ToString().Equals("1"))
    {
        badgeColor = "badge-warning";
        srcImage = "https://bootdey.com/img/Content/user_1.jpg";
        text = "Lãnh đạo";
    }
    else if (item.Role.ToString().Equals("2"))
    {
        badgeColor = "badge-info";
        srcImage = "https://www.bootdey.com/img/Content/avatar/avatar7.png";
        text = "Nhân viên";
    }
    else
    {
        badgeColor = "badge-danger";
        srcImage = "https://www.bootdey.com/img/Content/avatar/avatar6.png";
        text = "Ban điều hành";
    }

    <li class="media">
        <a href="#" class="pull-left">
            <img src="@srcImage" alt="" class="img-circle">
        </a>
        <div class="media-body">
            <span class="text-muted pull-right">
                <small class="text-muted"><time class="timeago" datetime="@item.TimeStamp"></time></small>
            </span>
            <strong class="text-success">@item.Name</strong>
            <br />
            <span class="badge badge-pill @badgeColor">@text</span>
            <br />
            <div style="word-wrap: break-word;">
                @item.Content
            </div>
            <br />
        </div>
    </li>
}
<script>
    $(document).ready(function () {
        $('time.timeago').timeago();
    });
</script>

ToDoList/Views/Shared/_IsActive.cshtml
@model bool
@if (Model == true)
{
    @Html.Encode("Active")
}
@if (Model == false)
{
    @Html.Encode("Inactive")
}

ToDoList/Views/Shared/_ModalView.cshtml
@model ToDoList.ViewModel.TaskIndexVM
<table class="table colored-header datatable project-list" id="dataTableSt">
    <thead class="thead-dark">
        <tr>
            <th>Tiêu đề</th>
            <th>Ngày bắt đầu</th>
            <th>Ngày kết thúc</th>
            <th>Phạm vi</th>
            <th>Trạng thái</th>
            <th>Hành động</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Tasks.Count <= 0)
            {
            <tr>
                <td colspan="7" style="text-align:center"><i>Không có công việc trễ hạn trong khoảng thời gian này</i></td>
            </tr>
        }
        @foreach (var item in Model.Tasks)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @{
                        var startDate = item.StartDate.ToString("dd/MM/yyyy HH:mm tt");
                        var endDate = item.EndDate.ToString("dd/MM/yyyy HH:mm tt");
                    }
                    @startDate
                </td>
                <td>
                    @endDate
                </td>
                <td>
                    @{
                        var lableColor = item.Scope ? "label-info" : "label-warning";
                        var textScope = item.Scope ? "public" : "private";
                    }
                    <div class="bootstrap-tagsinput">
                        <span class="tag label @lableColor">
                            @textScope
                            <span data-role="remove"></span>
                        </span>
                    </div>
                </td>
                <td>
                    @{
                        // 1. Đang làm  2. Đã xong  3. Trễ hạn
                        var labelStatusColor = "";
                        var statusText = item.StatusId.ToString();
                        if (statusText == "1")
                        {
                            labelStatusColor = "label-primary";
                            statusText = "Đang làm";
                        }
                        else if (statusText == "2")
                        {
                            labelStatusColor = "label-success";
                            statusText = "Đã xong";
                        }
                        else
                        {
                            labelStatusColor = "label-danger";
                            statusText = "Trễ hạn";
                        }
                    }
                    <div class="bootstrap-tagsinput">
                        <span class="tag label @labelStatusColor">
                            @statusText
                            <span data-role="remove"></span>
                        </span>
                    </div>
                </td>
                <td>
                    <a href="@Url.Action("Detail", "Task", new { id = @item.Id })" style="text-decoration:none"><button type="button" class="btn btn-outline-secondary">Chi tiết</button></a>
                </td>
            </tr>
    }
    </tbody>
</table>
@{
    var disNext = !Model.Tasks.HasNext ? " visibility: hidden" : "";
    var disPre = !Model.Tasks.HasPrevious ? " visibility: hidden" : "";
}

<ul id="detailExpiredTask" class="pagination justify-content-end" style="margin:20px 0">
    <li class="page-item">
        <a class="page-link" style="@disPre"
           data-pageIndex="@Model.Tasks.PageIndex - 1"><</a>
    </li>
    @{
        for (int i = 1; i <= Model.Tasks.TotalPages; i++)
        {
            //Nếu số tổng số trang >=8 thì sẽ hiện ... và sẽ hiện trang : i-2 , i-1 , i , i+1 ,i+2
            if (Model.Tasks.TotalPages >= 8 && @i >= Model.Tasks.PageIndex - 2 && @i <= Model.Tasks.PageIndex + 2)
            {
                if (@i == Model.Tasks.PageIndex - 2 && @i > 1)
                {
                    <li class="page-item"><a class="page-link">...</a></li>
                }
                if (@i == Model.Tasks.PageIndex)
                {
                    <li class="page-item active">
                        <a class="page-link "  data-pageIndex="@i"> @i </a>
                    </li>
                }
                else
                {
                    <li class="page-item ">
                        <a class="page-link"
                            data-pageIndex="@i">@i</a>
                    </li>
                }
                if (@i == Model.Tasks.PageIndex + 2 && @i < Model.Tasks.TotalPages)
                {
                    <li class="page-item"><a class="page-link">...</a></li>
                }
            }
            else if (Model.Tasks.TotalPages < 8) //Nếu số tổng số trang <8 thì sẽ hiện hết các trang
            {
                if (@i == Model.Tasks.PageIndex)
                {
                    <li class="page-item active">
                        <a class="page-link "  data-pageIndex="@i"> @i </a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a class="page-link"
                           data-pageIndex="@i">@i</a>
                    </li>
                }
            }
        }
    }
    <li class="page-item">
        <a class="page-link" style="@disNext"
           data-pageIndex="@Model.Tasks.PageIndex + 1">></a>
    </li>
</ul>

ToDoList/Views/Shared/_NVMenu.cshtml
<div class="list-group list-group-flush">
    <a href="@Url.Action("Index","Home")" class="list-group-item list-group-item-action bg-light">Trang chủ</a>
    <a href="@Url.Action("Index","Task")" class="list-group-item list-group-item-action bg-light">Quản lý công việc</a>
    <a href="@Url.Action("PublicTask","Task")" class="list-group-item list-group-item-action bg-light">Công việc public</a>
</div>

ToDoList/Views/Shared/_QTMenu.cshtml
<div class="list-group list-group-flush">
    <a href="@Url.Action("Index","Home")" class="list-group-item list-group-item-action bg-light">Trang chủ</a>
    <a href="@Url.Action("Index","Employee")" class="list-group-item list-group-item-action bg-light">Quản lý nhân viên</a>
    <a href="@Url.Action("Index","Task")" class="list-group-item list-group-item-action bg-light">Quản lý công việc</a>
    <a href="@Url.Action("Index", "Statistical")" class="list-group-item list-group-item-action bg-light">Thống kê</a>
</div>

ToDoList/Views/Shared/_SuperMenu.cshtml
<div class="list-group list-group-flush">
    <a href="@Url.Action("Index","Home")" class="list-group-item list-group-item-action bg-light">Trang chủ</a>
    <a href="@Url.Action("Index","SuperAdmin")" class="list-group-item list-group-item-action bg-light">Danh sách quản trị viên</a>
</div>

ToDoList/Views/Shared/_TableFilePartial.cshtml
@model ToDoList.ViewModel.TaskEditVM

<div class="assign-team mt-4 ">
    @*<h5 class="m-b-5">Danh sách tập tin đính kèm</h5>*@
    @Html.LabelFor(model => model.ListFile, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="table-responsive table-striped col-md-10">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>Mã File</th>
                    <th>Tên file</th>
                    <th>Thao tác</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ListFile)
                {
                    <tr>
                        <td>@item.Id </td>
                        <td>@item.C_Path </td>
                        <td class="btnDeleteFile" id="@item.Id" fileName="@item.C_Path" taskId="@item.TaskId"> DELETE </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>